# -*- coding: utf-8 -*-
"""Entrega_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rcPefW3lZxuHQGAOtRY4v9hxyjOsDW-S
"""

import pandas as pd
data = pd.read_csv('calles_de_medellin_con_acoso.csv', sep = ';')
data